# Generated by Django 2.0.2 on 2018-03-23 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_fecha_de_creacion', models.DateTimeField(verbose_name='fecha creacion')),
                ('tarea_fecha_de_vencimiento', models.DateTimeField(verbose_name='fecha vencimiento')),
                ('tarea_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
