# Generated by Django 2.0.2 on 2018-03-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tarea_descripcion',
            field=models.TextField(default=0.08333333333333333, verbose_name='descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_estado',
            field=models.BooleanField(default=1, verbose_name='finalizada'),
            preserve_default=False,
        ),
    ]
